return {}
-- return {
-- 	"folke/which-key.nvim",
-- 	event = "VeryLazy",
-- 	-- keys = {
-- 	-- 	{
-- 	-- 		"<leader>?",
-- 	-- 		function()
-- 	-- 			require("which-key").show({ global = false })
-- 	-- 		end,
-- 	-- 		desc = "Buffer Local Keymaps (which-key)",
-- 	-- 	},
-- 	-- },
-- 	opts = {
-- 		icons = {
-- 			mappings = false,
-- 			show_help = false,
-- 			show_keys = false,
-- 		},
-- 	},
-- 	config = function()
-- 		local wk = require("which-key")
--
-- 		-- Register mapping groups with keybindings
-- 		wk.add({
-- 			-- Open explorer
-- 			-- { "<leader>e", "<cmd>NvimTreeToggle<cr>", desc = "Explorer", icon = "" },
--
-- 			-- Find group
-- 			{ "<leader>f", group = "Find", icon = "" },
-- 			{ "<leader>ff", "<cmd>Telescope find_files<cr>", desc = "Find Files" },
-- 			{ "<leader>fd", "<cmd>Telescope live_grep<cr>", desc = "Live Grep" },
-- 			{ "<leader>fg", "<cmd>Telescope git_status<cr>", desc = "Git Status" },
--
-- 			-- Buffer Close group
-- 			{ "<leader>c", group = "Buffer Close", icon = "" },
-- 			{ "<leader>co", "<cmd>BufferCloseAllButCurrent<cr>", desc = "Close Others" },
-- 			{ "<leader>cc", "<cmd>BufferClose<cr>", desc = "Close Current" },
-- 			{ "<leader>cw", "<cmd>close<cr>", desc = "Close Window" },
--
-- 			{ "<leader>l", group = "LSP", icon = "" },
-- 			{ "<leader>lg", ":Lspsaga peek_definition<cr>", desc = "Peek Definition" },
--
-- 			-- Git
-- 			{ "<leader>g", group = "LSP" },
-- 			{ "<leader>gg", "<cmd>LazyGit<cr>", desc = "LazyGit" },
-- 		})
-- 	end,
-- }
